version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: galaxia
      MONGO_INITDB_ROOT_PASSWORD: galaxia123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
